### ISSUE TITLE
Lock Labels

### ISSUE THREAD

**Issue by duichwer** [SpareBrainedIdeas/Spare-Brained-Licensing#3]
I like your repo and maybe i find some time to test soon.
After looking into the code, I asked me if those labels shouldn't be set to locked=true..?

https://github.com/SpareBrainedIdeas/Spare-Brained-
Licensing/blob/dbdb1a370ebccd52bbc74deaa1e8561211c747e0/src/codeunit/SPBPLLicenseUtilities.Codeunit.al#L6

**Comment by JeremyVyska** [comment]
Almost certainly a true point.  Thanks!  I'll look to fixing that up shortly.

**Comment by JeremyVyska** [comment]
Wow, so... shortly wasn't so short.  But fixed now
