### ISSUE TITLE
Problem with Evaluate Active Value out of IsoStore

### ISSUE THREAD

**Issue by es-mh** [SpareBrainedIdeas/Spare-Brained-Licensing#5]
Hi,

when using the CheckIfActive procedure, I get an error when trying to read the active value out of the Isolated Store

Value "Ja" cannote be evaluated in Type Boolean...
I'm using an AT Version

Problem should be solved if formatting the value when writing in Codeunit SPBPL License Utilities, as you already did it with the DateTime Values
SPBPLIsoStoreManager.SetAppValue(SPBPLExtensionLicense, 'active', Format(SPBPLExtensionLicense.Activated**,0,9**));

Thanks,
Michael

**Comment by JeremyVyska** [comment]
Good catch, this is now in place.
