### ISSUE TITLE
Empty Page after navigating back from the final step

### ISSUE THREAD

**Issue by christianbraeunlich** [SpareBrainedIdeas/Spare-Brained-Licensing#6]
When navigating back via the **Back** action, an empty page is displayed.

Steps to reproduce:
1. Open Page **SPBPL Extension Licenses**
2. Select the **Spare Brained Licensing Public Test Subcription** Extension
3. Click on the **Activate** action.
4. Activate the Extension via **Use Test Key**
5. Click on the **Back** action after the "Activation Successful!" message is displayed on the final step

![grafik](https://user-images.githubusercontent.com/25108568/152401086-726f7551-0877-46b7-9cf4-6aa4337c7c12.png)

**Comment by JeremyVyska** [comment]
Thank you!  Added to core code.
