### ISSUE TITLE
Deaktivation does not work in trial period

### ISSUE THREAD

**Issue by StefanMaron** [SpareBrainedIdeas/Spare-Brained-Licensing#8]
When the trial period is still active, it is not possible to deaktivate the app.

In the overview of the extensions it will turn red and the trial date does not show anymore.
![image](https://user-images.githubusercontent.com/24838311/172040376-13c7aa5e-4b66-4411-8b29-b248735f4d46.png)

But the CheckIfActive will still return true.

I think if I manually hit disable for that app, it should not be active anymore. 
However it should still be possible to enable it again within the trial period.

**Comment by JeremyVyska** [comment]
100% correct.  I was delayed on Friday with the new release, but this should be fixed in the push that just came out.  Let me know if you still have the issue and I'll reopen and investigate.
